language: node_js
node_js:
  - 'node'
env:
  global:
    - CC_TEST_REPORTER_ID=$TEST_REPORTER_ID API_BASE_URL=https://krypton-ah-stage.herokuapp.com/api/v1 BASE_URL_CB=https://krypton-ah-fe-stage.herokuapp.com
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test -- -u
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
