const actionTypes = {
  FETCH_CATEGORIES_LOADING: 'CATEGORIES_LOADING',
  ADD_CATEGORIES_LOADING: 'CATEGORIES_LOADING',
  ADD_PRODUCTS_LOADING: 'CATEGORIES_LOADING',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  ADD_CATEGORIES_SUCCESS: 'ADD_CATEGORIES_SUCCESS',
  ADD_PRODUCTS_SUCCESS: 'ADD_PRODUCTS_SUCCESS',
  ADD_PRODUCTS_FAILURE: 'ADD_PRODUCTS_FAILURE',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
  ADD_CATEGORIES_FAILURE: 'ADD_CATEGORIES_FAILURE',
};

export default actionTypes;
