const actionTypes = {
  PRODUCTS_LOADING: 'PRODUCTS_LOADING',
  FETCH_PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'PRODUCTS_FAILURE',
  SALES_LOADING: 'SALES_LOADING',
  FETCH_SALES_SUCCESS: 'SALES_SUCCESS',
  FETCH_SALES_FAILURE: 'SALES_FAILURE',
};

export default actionTypes;
